package pl.robert.project.validation;

public interface ValidationStrings {

    String F_CONFIRMED_PASSWORD = "confirmedPassword";
    String F_CONFIRMED_EMAIL = "confirmedEmail";
    String F_CONFIRMED_PHONE_NUMBER = "confirmedPhoneNumber";
    String F_RECEIVER_ACCOUNT_NUMBER = "receiverAccountNumber";
    String F_AMOUNT = "amount";
    String F_FORGOTTEN_LOGIN_OR_PASSWORD = "forgottenEmail";

    String C_CONFIRMED_PASSWORD_NOT_MATCH = "C_CONFIRMED_PASSWORD_NOT_MATCH";
    String C_CONFIRMED_EMAIL_NOT_MATCH = "C_CONFIRMED_EMAIL_NOT_MATCH";
    String C_CONFIRMED_PHONE_NUMBER_NOT_MATCH = "C_CONFIRMED_PHONE_NUMBER_NOT_MATCH";
    String C_RECEIVER_ACCOUNT_NUMBER_NOT_EXISTS = "C_RECEIVER_ACCOUNT_NUMBER_NOT_EXISTS";
    String C_RECEIVER_ACCOUNT_NUMBER_MATCH_SENDER = "C_RECEIVER_ACCOUNT_NUMBER_MATCH_SENDER";
    String C_AMOUNT_NOT_ENOUGH = "C_AMOUNT_NOT_ENOUGH";
    String C_FORGOTTEN_LOGIN_OR_PASSWORD = "C_FORGOTTEN_LOGIN_OR_PASSWORD";
    String C_CLASS_INSTANCE_NOT_MATCH = "C_CLASS_INSTANCE_NOT_MATCH";
}
