spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddlAuto: create
    showSql: true
    openInView: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    #username:
    #password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
